#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: network

# STEP: vivado_flow
cd /home/socks/neural-network-fpga/main-branch/src/hdl
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/socks/neural-network-fpga/main-branch/src/hdl/HLS_output//Synthesis/vivado_flow/vivado.tcl


