#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: main

# STEP: vivado_flow
cd /home/kiit2951/Desktop/Logistic_Regression_HLS_bambu
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/kiit2951/Desktop/Logistic_Regression_HLS_bambu/HLS_output//Synthesis/vivado_flow_9/vivado.tcl


