#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: main

# STEP: vivado_flow
cd /home/kiit2951/Desktop/Verilog_ML/simple_neural_network/HLS
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/kiit2951/Desktop/Verilog_ML/simple_neural_network/HLS/HLS_output//Synthesis/vivado_flow/vivado.tcl


